spring.application.name=journalApp
spring.data.mongodb.uri=mongodb+srv://Amruta:Amruta%40123@cluster0.ykqqacu.mongodb.net/Journal?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true